// Mocks generated by Mockito 5.4.4 from annotations
// in monobox/test/features/basket/data/repository/basket_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:flutter_bloc/flutter_bloc.dart' as _i23;
import 'package:mockito/mockito.dart' as _i1;
import 'package:monobox/features/address_setup/domain/entities/address_entity.dart'
    as _i20;
import 'package:monobox/features/basket/data/data_sources/locale/basket_locale.dart'
    as _i17;
import 'package:monobox/features/basket/data/models/basket_offer_dto.dart'
    as _i18;
import 'package:monobox/features/more/domain/entities/shop_entity.dart' as _i21;
import 'package:monobox/features/order/data/datasources/remote/order_api_service.dart'
    as _i9;
import 'package:monobox/features/order/data/models/basket_info_dto.dart' as _i5;
import 'package:monobox/features/order/data/models/basket_info_request_basket_dto.dart'
    as _i16;
import 'package:monobox/features/order/data/models/gifts_dto.dart' as _i4;
import 'package:monobox/features/order/data/models/gifts_scale_item_dto.dart'
    as _i13;
import 'package:monobox/features/order/data/models/order_create_request_dto.dart'
    as _i11;
import 'package:monobox/features/order/data/models/order_create_response_dto.dart'
    as _i2;
import 'package:monobox/features/order/data/models/order_details_dto.dart'
    as _i3;
import 'package:monobox/features/order/data/models/order_dto.dart' as _i12;
import 'package:monobox/features/order/data/models/payment_url_dto.dart' as _i7;
import 'package:monobox/features/order/data/models/promocode_dto.dart' as _i6;
import 'package:monobox/features/order/data/models/upsale_request_dto.dart'
    as _i15;
import 'package:monobox/features/order/data/models/upsales_dto.dart' as _i14;
import 'package:monobox/features/order/domain/entities/delivery_entity.dart'
    as _i22;
import 'package:monobox/features/order/presentation/bloc/create_order_state_cubit/create_order_state_cubit.dart'
    as _i19;
import 'package:monobox/features/order/presentation/models/create_order_state.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrderCreateResponseDto_0 extends _i1.SmartFake
    implements _i2.OrderCreateResponseDto {
  _FakeOrderCreateResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderDetailsDto_1 extends _i1.SmartFake
    implements _i3.OrderDetailsDto {
  _FakeOrderDetailsDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGiftsDto_2 extends _i1.SmartFake implements _i4.GiftsDto {
  _FakeGiftsDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBasketInfoDto_3 extends _i1.SmartFake implements _i5.BasketInfoDto {
  _FakeBasketInfoDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromocodeDto_4 extends _i1.SmartFake implements _i6.PromocodeDto {
  _FakePromocodeDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentUrlDto_5 extends _i1.SmartFake implements _i7.PaymentUrlDto {
  _FakePaymentUrlDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateOrderState_6 extends _i1.SmartFake
    implements _i8.CreateOrderState {
  _FakeCreateOrderState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderApiService extends _i1.Mock implements _i9.OrderApiService {
  MockOrderApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.OrderCreateResponseDto> create(
          _i11.OrderCreateRequestDto? orderCreateRequestDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [orderCreateRequestDto],
        ),
        returnValue: _i10.Future<_i2.OrderCreateResponseDto>.value(
            _FakeOrderCreateResponseDto_0(
          this,
          Invocation.method(
            #create,
            [orderCreateRequestDto],
          ),
        )),
      ) as _i10.Future<_i2.OrderCreateResponseDto>);

  @override
  _i10.Future<List<_i12.OrderDto>> getOrders() => (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
        ),
        returnValue: _i10.Future<List<_i12.OrderDto>>.value(<_i12.OrderDto>[]),
      ) as _i10.Future<List<_i12.OrderDto>>);

  @override
  _i10.Future<_i3.OrderDetailsDto> getOrder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [id],
        ),
        returnValue:
            _i10.Future<_i3.OrderDetailsDto>.value(_FakeOrderDetailsDto_1(
          this,
          Invocation.method(
            #getOrder,
            [id],
          ),
        )),
      ) as _i10.Future<_i3.OrderDetailsDto>);

  @override
  _i10.Future<void> deleteOrder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteOrder,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i4.GiftsDto> gifts(
          _i11.OrderCreateRequestDto? orderCreateRequestDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #gifts,
          [orderCreateRequestDto],
        ),
        returnValue: _i10.Future<_i4.GiftsDto>.value(_FakeGiftsDto_2(
          this,
          Invocation.method(
            #gifts,
            [orderCreateRequestDto],
          ),
        )),
      ) as _i10.Future<_i4.GiftsDto>);

  @override
  _i10.Future<List<_i13.GiftsScaleItemDto>> giftsScale() => (super.noSuchMethod(
        Invocation.method(
          #giftsScale,
          [],
        ),
        returnValue: _i10.Future<List<_i13.GiftsScaleItemDto>>.value(
            <_i13.GiftsScaleItemDto>[]),
      ) as _i10.Future<List<_i13.GiftsScaleItemDto>>);

  @override
  _i10.Future<List<_i14.UpsalesDto>> upsale(
          _i15.UpsaleRequestDto? upsaleRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsale,
          [upsaleRequest],
        ),
        returnValue:
            _i10.Future<List<_i14.UpsalesDto>>.value(<_i14.UpsalesDto>[]),
      ) as _i10.Future<List<_i14.UpsalesDto>>);

  @override
  _i10.Future<_i5.BasketInfoDto> basketInfo(
          _i16.BasketInfoRequestBasketDto? basketInfoReques) =>
      (super.noSuchMethod(
        Invocation.method(
          #basketInfo,
          [basketInfoReques],
        ),
        returnValue: _i10.Future<_i5.BasketInfoDto>.value(_FakeBasketInfoDto_3(
          this,
          Invocation.method(
            #basketInfo,
            [basketInfoReques],
          ),
        )),
      ) as _i10.Future<_i5.BasketInfoDto>);

  @override
  _i10.Future<_i6.PromocodeDto> getPromocode(String? promocode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPromocode,
          [promocode],
        ),
        returnValue: _i10.Future<_i6.PromocodeDto>.value(_FakePromocodeDto_4(
          this,
          Invocation.method(
            #getPromocode,
            [promocode],
          ),
        )),
      ) as _i10.Future<_i6.PromocodeDto>);

  @override
  _i10.Future<_i7.PaymentUrlDto> getPaymentUrl(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentUrl,
          [id],
        ),
        returnValue: _i10.Future<_i7.PaymentUrlDto>.value(_FakePaymentUrlDto_5(
          this,
          Invocation.method(
            #getPaymentUrl,
            [id],
          ),
        )),
      ) as _i10.Future<_i7.PaymentUrlDto>);
}

/// A class which mocks [BasketLocale].
///
/// See the documentation for Mockito's code generation for more information.
class MockBasketLocale extends _i1.Mock implements _i17.BasketLocale {
  MockBasketLocale() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> initBox() => (super.noSuchMethod(
        Invocation.method(
          #initBox,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addBasketItem(_i18.BasketOfferDto? offer) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBasketItem,
          [offer],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeBasketItem(_i18.BasketOfferDto? offer) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBasketItem,
          [offer],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i18.BasketOfferDto> getAllBasketItems() => (super.noSuchMethod(
        Invocation.method(
          #getAllBasketItems,
          [],
        ),
        returnValue: <_i18.BasketOfferDto>[],
      ) as List<_i18.BasketOfferDto>);

  @override
  _i10.Future<void> removeAllBasketItems() => (super.noSuchMethod(
        Invocation.method(
          #removeAllBasketItems,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [CreateOrderStateCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateOrderStateCubit extends _i1.Mock
    implements _i19.CreateOrderStateCubit {
  MockCreateOrderStateCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get deliveryTimes => (super.noSuchMethod(
        Invocation.getter(#deliveryTimes),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i8.CreateOrderState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeCreateOrderState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i8.CreateOrderState);

  @override
  _i10.Stream<_i8.CreateOrderState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<_i8.CreateOrderState>.empty(),
      ) as _i10.Stream<_i8.CreateOrderState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void setDeliveryAddress(_i20.AddressEntity? deliveryAddress) =>
      super.noSuchMethod(
        Invocation.method(
          #setDeliveryAddress,
          [deliveryAddress],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDeliveryDeliveryTime(String? deliveryTime) => super.noSuchMethod(
        Invocation.method(
          #setDeliveryDeliveryTime,
          [deliveryTime],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDeliveryDate(DateTime? deliveryDate) => super.noSuchMethod(
        Invocation.method(
          #setDeliveryDate,
          [deliveryDate],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDeliveryShop(_i21.ShopEntity? shop) => super.noSuchMethod(
        Invocation.method(
          #setDeliveryShop,
          [shop],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDeliveryTime(DateTime? deliveryTime) => super.noSuchMethod(
        Invocation.method(
          #setDeliveryTime,
          [deliveryTime],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDelivery(_i22.DeliveryEntity? delivery) => super.noSuchMethod(
        Invocation.method(
          #setDelivery,
          [delivery],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDeliveryTimeTypeIndex(int? deliveryTimeTypeIndex) =>
      super.noSuchMethod(
        Invocation.method(
          #setDeliveryTimeTypeIndex,
          [deliveryTimeTypeIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPaymentMethodIndex(int? paymentMethodIndex) => super.noSuchMethod(
        Invocation.method(
          #setPaymentMethodIndex,
          [paymentMethodIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUseBonuses(bool? use) => super.noSuchMethod(
        Invocation.method(
          #setUseBonuses,
          [use],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMakeCall(bool? makeCall) => super.noSuchMethod(
        Invocation.method(
          #setMakeCall,
          [makeCall],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeItogoIsCollapsed() => super.noSuchMethod(
        Invocation.method(
          #changeItogoIsCollapsed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStayNearDoor(bool? stayNearDoor) => super.noSuchMethod(
        Invocation.method(
          #setStayNearDoor,
          [stayNearDoor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isAllowToCreate() => (super.noSuchMethod(
        Invocation.method(
          #isAllowToCreate,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void emit(_i8.CreateOrderState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i23.Change<_i8.CreateOrderState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
